name: Build ZMK left firmware

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build-left:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your ZMK config
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Clone latest ZMK main
        run: |
          git clone --depth 1 https://github.com/zmkfirmware/zmk.git zmk

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip ninja-build git cmake dfu-util
          pip3 install west

      - name: Initialise Zephyr workspace
        run: |
          west init -l zmk/app        # create .west in repo root
          west update                 # fetch Zephyr + modules
          west zephyr-export          # export Zephyr CMake path

      - name: Build LEFT firmware
        run: |
          west build -p always -s zmk/app -d build/left -b nice_nano_v2 \
            -- -DZMK_CONFIG=config -DSHIELD=jsouryado_left
          cp build/left/zephyr/zmk.uf2 firmware-jsouryado-left-nice_nano_v2.uf2

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: jsouryado-left
          path: firmware-jsouryado-left-nice_nano_v2.uf2
